# 1. Create a 3x3x3 array with random values 

In [3]:
import numpy as np

In [10]:
a = np.random.random((3,3,3))

In [11]:
a

array([[[0.37869769, 0.25410732, 0.56981824],
        [0.67163018, 0.34988429, 0.23296033],
        [0.39347691, 0.43519679, 0.16574048]],

       [[0.38861853, 0.90193677, 0.38558964],
        [0.0040008 , 0.63456303, 0.1039468 ],
        [0.47883878, 0.44185383, 0.97189817]],

       [[0.76871221, 0.86038817, 0.67436619],
        [0.67279955, 0.88073852, 0.19185364],
        [0.58806404, 0.3427373 , 0.14354093]]])

In [12]:
a.shape

(3, 3, 3)

# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [25]:
Z = np.diag(1+np.arange(4),k=-1)

print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [13]:
x = np.ones((3,3))
print("Checkerboard pattern:")
x = np.zeros((8,8),dtype=int)
x[1::2,::2] = 1
x[::2,1::2] = 1
print(x)

Checkerboard pattern:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# 4. Normalize a 5x5 random matrix

In [15]:
y= np.random.random((5,5))
print("Original Array:")
print(y)
ymax, ymin = y.max(), y.min()
y = (y - ymin)/(ymax - ymin)
print("After normalization:")
print(y)

Original Array:
[[0.74437119 0.98698483 0.3606131  0.86552921 0.50294541]
 [0.18053713 0.61369822 0.53672459 0.44052193 0.62189759]
 [0.26443336 0.0536107  0.36719278 0.60616695 0.02334276]
 [0.16252349 0.68297094 0.62051844 0.286616   0.71292617]
 [0.6226211  0.4374924  0.50118156 0.12574541 0.5238558 ]]
After normalization:
[[0.74823262 1.         0.34999544 0.8739619  0.49769791]
 [0.16312526 0.61262939 0.53275158 0.43291922 0.62113813]
 [0.25018688 0.03140994 0.35682338 0.60481398 0.        ]
 [0.14443197 0.68451575 0.61970694 0.27320646 0.71560118]
 [0.62188893 0.42977538 0.49586751 0.10626627 0.51939725]]


# 5.  How to find common values between two arrays?

In [16]:
array1 = np.array([0, 10, 20, 40, 60])
print("Array1: ",array1)
array2 = [10, 30, 40]
print("Array2: ",array2)
print("Common values between two arrays:")
print(np.intersect1d(array1, array2))

Array1:  [ 0 10 20 40 60]
Array2:  [10, 30, 40]
Common values between two arrays:
[10 40]


# 6.How to get the dates of yesterday, today and tomorrow?

In [17]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yestraday: ",yesterday)
today     = np.datetime64('today', 'D')
print("Today: ",today)
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tomorrow: ",tomorrow)

Yestraday:  2020-07-25
Today:  2020-07-26
Tomorrow:  2020-07-27


# 7. Consider two random array A and B, check if they are equal

In [18]:
x1 = np.random.randint(0,2,6)
print("First array:")
print(x1)
y1 = np.random.randint(0,2,6)
print("Second array:")
print(y1)
print("Are the two arrays equal?")
array_equal = np.allclose(x1, y1)
print(array_equal)

First array:
[1 1 0 0 0 1]
Second array:
[1 1 1 1 0 1]
Are the two arrays equal?
False


# 8.Create random vector of size 10 and replace the maximum value by 0 

In [19]:
z = np.random.random(10)
print("Original array:")
print(z)
z[z.argmax()] = 0
print("Maximum value replaced by 0:")
print(z)

Original array:
[0.08420664 0.12244045 0.02787043 0.40060383 0.63636488 0.39886485
 0.67278139 0.42320357 0.329019   0.76412259]
Maximum value replaced by 0:
[0.08420664 0.12244045 0.02787043 0.40060383 0.63636488 0.39886485
 0.67278139 0.42320357 0.329019   0.        ]


# 9. How to print all the values of an array?

In [28]:
np.set_printoptions(threshold=np.inf)

Z1 = np.zeros((12,12))

print(Z1)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


# 10.Subtract the mean of each row of a matrix

In [24]:
print("Original matrix:\n")
X = np.random.rand(5, 10)
print(X)
print("\nSubtracted matrix:\n")
Y = X - X.mean(axis=1, keepdims=True)
print(Y)

Original matrix:

[[0.36940432 0.85650612 0.19377257 0.87438833 0.29402782 0.51855166
  0.27883907 0.33267474 0.98077727 0.40709865]
 [0.98401618 0.75528077 0.41842121 0.92367517 0.23572208 0.20040999
  0.58855507 0.95803877 0.65952337 0.40347811]
 [0.74660503 0.6473661  0.57827526 0.78565612 0.60609365 0.03806528
  0.21006664 0.76513316 0.13519502 0.53604302]
 [0.55940597 0.47565623 0.21608475 0.28178103 0.65613653 0.61796931
  0.21502022 0.715253   0.58341808 0.36245097]
 [0.05032317 0.84387872 0.661464   0.37835121 0.80289929 0.18564408
  0.96767286 0.27983544 0.05346049 0.14282892]]

Subtracted matrix:

[[-0.14119974  0.34590206 -0.31683148  0.36378427 -0.21657624  0.00794761
  -0.23176498 -0.17792931  0.47017321 -0.10350541]
 [ 0.3713041   0.1425687  -0.19429086  0.3109631  -0.37698999 -0.41230208
  -0.024157    0.34532669  0.0468113  -0.20923396]
 [ 0.2417551   0.14251617  0.07342533  0.2808062   0.10124372 -0.46678465
  -0.29478329  0.26028324 -0.36965491  0.03119309]
 [ 0.09108

# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

# 12.How to get the diagonal of a dot product?

In [31]:
A = np.random.uniform(0,1,(5,5))

B = np.random.uniform(0,1,(5,5))

np.diag(np.dot(A, B))

array([2.62731183, 1.52925336, 1.37927059, 1.1608938 , 1.58919845])

# 13.How to find the most frequent value in an array?

In [34]:
s = np.random.randint(0, 10, 40)
print("Original array:")
print(s)
print("Most frequent value in the above array:")
print(np.bincount(s).argmax())

Original array:
[0 4 9 9 0 3 7 3 8 4 1 0 4 6 5 4 4 6 3 1 7 2 7 6 2 3 9 7 5 6 2 5 8 5 8 1 1
 4 7 4]
Most frequent value in the above array:
4


# 14.How to get the n largest values of an array

In [37]:
p = np.arange(10)
print("Original array:")
print(p)
np.random.shuffle(p)
n = 2
print (p[np.argsort(p)[-n:]])

Original array:
[0 1 2 3 4 5 6 7 8 9]
[8 9]


# 15.How to create a record array from a regular array?

In [39]:
Q = np.array([("Hello", 2.5, 3),

("World", 3.6, 2)])
print("Original array: ")
print(Q)

R = np.core.records.fromarrays(Q.T,

names='col1, col2, col3',

formats = 'S8, f8, i8')
print("Record array: ")
print(R)

Original array: 
[['Hello' '2.5' '3']
 ['World' '3.6' '2']]
Record array: 
[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]
